#!/bin/bash -*- mode: sh -*-
#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '

[[ -d ~/.profile.d ]] && for x in ~/.profile.d/*.sh; do source $x; done

# don't put duplicate lines in the history. See bash(1) for more options
# don't overwrite GNU Midnight Commander's setting of `ignorespace'.
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups

# append to the history file, don't overwrite it
[ -z "$ZSH_NAME" ] && shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
[ -z "$ZSH_NAME" ] && shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm* | rxvt*)
    PS1="\[\e]0;\u@\h: \w\a\]$PS1"
    ;;
*) ;;
esac

if [[ ${OS_CLASS} == "Linux" ]]; then
    # https://wiki.archlinux.org/index.php/GnuPG#SSH_agent
    unset SSH_AGENT_PID
    echo ${SSH_AUTH_SOCK:=${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh} >/dev/null

    LC_NUMERIC=fr_FR.UTF-8
    LC_TIME=fr_FR.UTF-8
    LC_MONETARY=fr_FR.UTF-8
    LC_PAPER=fr_FR.UTF-8
    LC_NAME=fr_FR.UTF-8
    LC_ADDRESS=fr_FR.UTF-8
    LC_TELEPHONE=fr_FR.UTF-8
    LC_MEASUREMENT=fr_FR.UTF-8
    LC_IDENTIFICATION=fr_FR.UTF-8
    PAPERSIZE=a4

    export SSH_AUTH_SOCK LC_NUMERIC LC_TIME LC_MONETARY LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION PAPERSIZE
fi

# enable color support of ls and also add handy aliases
if type dircolors >/dev/null 2>&1; then
    eval "$(dircolors -b)"
    alias ls='ls --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# libvirt needs a relaxed umask, 0002, however not using that currently
# Base setting on Linux is through pam_umask + /etc/login.defs
# Not sharing machines currently, so let just use the system default
#umask 0077

export EDITOR=vim

[[ -z "$TMPDIR" ]] && export TMPDIR="/tmp/$USER"
[[ ! -d "$TMPDIR" ]] && mkdir -m 700 "$TMPDIR" && export TMPDIR="/tmp/$USER"

if [ -z "$ZSH_NAME" ]; then
    # Git prompt configuration

    function source_git_prompt() {
        local bashrc_dir=$(dirname $(readlink -f ${BASH_SOURCE[0]}))

        if [[ -f $bashrc_dir/git-prompt.sh ]]; then
            source $bashrc_dir/git-prompt.sh
        else
            source /usr/share/git/completion/git-prompt.sh
        fi
    }

    source_git_prompt

    export GIT_PS1_SHOWDIRTYSTATE=1
    export GIT_PS1_SHOWSTASHSTATE=1
    export GIT_PS1_SHOWUNTRACKEDFILES=1
    export GIT_PS1_SHOWUPSTREAM="auto verbose name"
    export GIT_PS1_SHOWCOLORHINTS=1

    # Python virtualenv prompt configuration
    # Based on http://stackoverflow.com/a/20026992/3023502
    export VIRTUAL_ENV_DISABLE_PROMPT=1

    function python_virtualenv() {
        if [[ -n "$VIRTUAL_ENV" ]]; then
            # Strip out the path and just leave the env name
            echo "(${VIRTUAL_ENV##*/})"
        fi
    }

    # Timestamp to calculate command duration
    PS0='$(touch $TMPDIR/.bash.cmd.start.pid.$$)'

    set_prompt() {
        Last_Command=$? # Must come first!

        starttime=$(stat --format="%Y" $TMPDIR/.bash.cmd.start.pid.$$ 2>/dev/null)
        if [[ -n $starttime ]]; then
            duration=$(date "+%s" -d "now -$starttime seconds")
            rm $TMPDIR/.bash.cmd.start.pid.$$
        else
            duration=
        fi

        Blue='\e[01;34m'
        White='\e[01;37m'
        Red='\e[01;31m'
        Green='\e[01;32m'
        Yellow='\e[01;33m'
        Magenta='\e[01;35m'
        Cyan='\e[01;36m'
        Reset='\e[00m'
        FancyX='\342\234\227'
        Checkmark='\342\234\223'

        prompt=""
        # If last command was successful, print a green check
        # mark. Otherwise, print a red X.
        if [[ $Last_Command == 0 ]]; then
            prompt+="$Green[ $Checkmark "
        else
            prompt+="$Red[ $FancyX "
        fi

        [[ -n "$duration" ]] && prompt+="$duration"' '
        prompt+="]"

        # and reset the text color to the default.
        prompt+="$Reset"

        printf "$prompt"
    }

    PROMPT_COMMAND='__git_ps1 "\n\$(set_prompt) \[\e[01;36m\]\u@\h \[\e[01;37m\]\w\[\e[00m\] \[\e[01;33m\]\$(python_virtualenv)\[\e[00m\]" "\n\[\e[01;35m\]❱\[\e[00m\] "'

    if [[ $PS1 ]]; then
        [ -f /usr/share/bash-completion/bash_completion ] && source /usr/share/bash-completion/bash_completion
        [ -f ~/.fzf.bash ] && source ~/.fzf.bash
    fi
fi

for d in ~/bin ~/.ghcup/bin ~/.cargo/bin ~/.global_npm/bin; do
    [[ -d $d ]] && export PATH=$PATH:$d
done

for d in ~/.go/bin ~/.ms-vscode/VSCode-linux-x64 /opt/homebrew/opt/llvm/bin /opt/homebrew/opt/openjdk/bin $HOME/.local/bin; do
    [[ -d $d ]] && export PATH=$d:$PATH
done

alias gls='git log --graph --decorate --date=relative --format="%C(yellow)%h%C(reset) %C(green)%cr%Creset %s%C(bold red)%d%C(white) [%aN]%C(reset)"'
alias gla='git log --graph --decorate --date=relative --format="%C(yellow)%h%C(reset) %C(green)%cr%Creset %s%C(bold red)%d%C(white) [%aN]%C(reset)" --all'
alias gv='git describe --tags --always --dirty'
# shellcheck disable=SC2142
alias grel='_gitlog(){ git log $1^..$2 --pretty=oneline --graph --decorate --no-merges } ; _gitlog'
alias gwl='git worktree list'
alias gw='git wip'
# Git clean pruned+merged branches
alias gcdb='git checkout master && git fetch --prune --all && git branch --merged | grep -v \* | xargs -r -- git branch -d'

alias doSshFS='echo sshfs -o transform_symlinks user@machine:/ ~/sshfs_mount/'
alias doScreen='echo ssh -t user@machine screen -D -RR'
alias smtpclient_test='echo gnutls-cli -V --crlf --starttls some_smtp_mailhub --port 587'
alias smtpclient_test2='echo gnutls-cli --crlf --starttls some_smtp_mailhub --port 587 --insecure'
alias dockerlogin='echo curl --insecure --user emountain https://dockerhub.wherever:5000/v2/auth'
alias bashtcp='exec 5<> /dev/tcp/myhost.com/80 ; cat <&5 & ; printf "GET / HTTP/1.0\r\n\r\n" >&5'

alias k='kubectl'
alias kg='kubectl get'
alias kgp='kubectl get pod'
alias kd='kubectl describe'
alias kdp='kubectl describe pod'
# shellcheck disable=SC2142
alias ksns='_ksns(){ kubectl config set-context --current --namespace=$1 } ; _ksns'
# shellcheck disable=SC2142
alias kngp='_kngp(){ kubectl get pods --field-selector=spec.nodeName=$1 --all-namespaces --no-headers -owide } ; _kngp'
alias kgpw='kubectl get pods -owide'
alias kgpww='kubectl get pods -owide -w'
alias kgpy='kubectl get pods -oyaml'
alias knodeinfo="kubectl get nodes -o custom-columns='Name:metadata.name,Kernel:status.nodeInfo.kernelVersion,Kubelet:status.nodeInfo.kubeletVersion,Runtime:status.nodeInfo.containerRuntimeVersion,Distrib:status.nodeInfo.osImage,Instance:metadata.labels.beta\.kubernetes\.io/instance-type' --sort-by=.metadata.creationTimestamp"

# git machete branch cleanup
alias gmbc='gl ; git machete slide-out --removed-from-remote && git machete delete-unmanaged'
# git machete create PR
alias gmcpr='git machete github create-pr && git machete github anno-prs --with-urls'
# git machete rebase all
alias gmra='git machete traverse -yW'
# git machete new branch
alias gmnb='git machete add -y'

# Get the list of containers running on a node using host-net
_kube-get-node-hostnet-containers() {
  kubectl get pods -A --field-selector spec.nodeName=$1 -ojson | jq '.items[] | select( .spec.hostNetwork == true ) | .spec.containers[].name'
}

_kube-check-metadata-server-all-nodes() {
  while read -r node zone nodeip ; do
    if ssh -T -n -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $nodeip  -- curl -s 169.254.169.254 >/dev/null 2>&1 ; then
      echo "node $node in $zone is OK"
    else
      echo "node $node in $zone is BROKEN"
    fi
  done < <(k get node -o json | jq -r '.items[] | "\(.metadata.name) \(.metadata.labels["topology.kubernetes.io/zone"]) \(.status.addresses[] | select(.type == "InternalIP") | .address)"')
}

firefox_mem_usage() {
    ps -Ao pid,pmem,comm | grep Web | grep -v Qt | awk 'BEGIN {a = 0}; {a += $2; print}; END {print a}'
}

_kube-new-worktree() {
    if [ ! -d ~/dev/go/kubernetes-$1/go/src/k8s.io/kubernetes ]; then
        cd ~/dev/go/kubernetes/go/src/k8s.io/kubernetes && git worktree add ~/dev/go/kubernetes-$1/go/src/k8s.io/kubernetes $1
    fi
    cd ~/dev/go/kubernetes-$1/go/src/k8s.io/kubernetes
}
alias kube-new-worktree='_kube-new-worktree'
